name: myenv

dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - gunicorn
  - Werkzeug
  - WTForms
  - SQLAlchemy
  - alembic
  - Flask
  - uwsgi
  - email_validator
  - PyYAML
  - pip
  - pip:
      - newspaper3k
      - gnews
      - lxml_html_clean
      - Flask_SQLAlchemy
      - Flask_WTF
      - Flask_Login
      - Flask_Migrate
      - fhirclient==3.2
